version: "3"
volumes:
  nginx_conf:
  media:
  static:
  postgres_data:
services:
  db:
    image: postgres:12
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
  web:
    #image: toshiharu13/star_burger
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    expose:
      - "8000"
    volumes:
      - media:/opt/star-burger/media
      - static:/opt/star-burger/staticfiles
  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - web
    volumes:
      - static:/var/html/static/
      - media:/var/html/media/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
