# Generated by Django 3.2 on 2022-02-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_foodorder_foodorderproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodorder',
            old_name='phone_number',
            new_name='phonenumber',
        ),
    ]
