# Generated by Django 3.2 on 2022-03-10 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_rename_phone_number_foodorder_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorderproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена'),
            preserve_default=False,
        ),
    ]
