# Generated by Django 3.2 on 2022-03-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_foodorderproduct_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodorderproduct',
            options={'verbose_name': 'Элементы заказа', 'verbose_name_plural': 'Элементы заказа'},
        ),
    ]
