# Generated by Django 3.2 on 2022-03-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_alter_foodorderproduct_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='order_status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('PROGRESS', 'В работе'), ('FINISHED', 'Закончен')], default='NEW', max_length=10),
        ),
    ]
