# Generated by Django 3.2 on 2022-03-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_foodorder_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='order_status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('PROGRESS', 'В работе'), ('FINISHED', 'Закончен')], db_index=True, default='NEW', max_length=10),
        ),
    ]
