# Generated by Django 3.2 on 2022-03-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20220323_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания заказа'),
        ),
    ]
