# Generated by Django 3.2 on 2022-03-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_foodorder_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='call_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда позвонить'),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда доставить'),
        ),
    ]
