# Generated by Django 3.2 on 2022-03-24 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_alter_foodorder_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodcartapp.restaurantmenuitem', verbose_name='Ресторан, выполняющий заказ'),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Наличными'), ('CARD', 'Картой')], db_index=True, max_length=10, verbose_name='Способ оплаты'),
        ),
    ]
