# Generated by Django 3.2 on 2022-03-24 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20220324_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodcartapp.restaurantmenuitem', verbose_name='Ресторан, выполняющий заказ'),
        ),
    ]
