# Generated by Django 3.2 on 2022-03-24 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_alter_foodorder_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodcartapp.restaurant', verbose_name='Ресторан, выполняющий заказ'),
        ),
    ]
