# Generated by Django 3.2 on 2022-03-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_auto_20220325_1310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сoordinate',
            new_name='Coordinate',
        ),
        migrations.AlterModelOptions(
            name='coordinate',
            options={'verbose_name': 'Координаты', 'verbose_name_plural': 'Координаты'},
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='сoordinate',
            new_name='coordinate',
        ),
    ]
