# Generated by Django 3.2 on 2022-03-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_auto_20220325_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinate',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
