# Generated by Django 3.2 on 2022-04-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_coordinate_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='lat',
            field=models.FloatField(null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='lon',
            field=models.FloatField(null=True, verbose_name='Долгота'),
        ),
    ]
