# Generated by Django 3.2 on 2022-04-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_auto_20220405_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адресс'),
        ),
    ]
