# Generated by Django 3.2 on 2022-04-12 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0059_alter_foodorder_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='creation_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время создания заказа'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=100, verbose_name='адрес'),
        ),
    ]
