# Generated by Django 3.2 on 2022-04-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0060_auto_20220412_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodorder',
            old_name='recommended_restaurant',
            new_name='recommended_restaurants',
        ),
    ]
