# Generated by Django 3.2 on 2022-04-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0061_rename_recommended_restaurant_foodorder_recommended_restaurants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='foodcartapp.foodorder', verbose_name='Заказ'),
        ),
    ]
