# Generated by Django 3.2 on 2022-04-14 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0062_alter_foodorderproduct_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_orders', to='foodcartapp.product', verbose_name='Продукты заказа'),
        ),
    ]
