# Generated by Django 3.2 on 2022-04-21 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0063_alter_foodorderproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_order_products', to='foodcartapp.foodorder', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='foodorderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_order_products', to='foodcartapp.product', verbose_name='Продукты заказа'),
        ),
    ]
