# Generated by Django 3.2 on 2022-05-08 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0064_auto_20220421_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='assigned_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodcartapp.restaurant', verbose_name='Назначеный ресторан'),
        ),
    ]
