# Generated by Django 3.2 on 2022-05-08 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0065_foodorder_assigned_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='assigned_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.restaurant', verbose_name='Назначеный ресторан'),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='recommended_restaurants',
            field=models.ManyToManyField(blank=True, related_name='food_orders', to='foodcartapp.Restaurant', verbose_name='Рекомендованые рестораны'),
        ),
    ]
