# Generated by Django 3.2 on 2022-05-10 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0066_auto_20220508_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='assigned_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_for_food_orders', to='foodcartapp.restaurant', verbose_name='Назначеный ресторан'),
        ),
    ]
