# Generated by Django 3.2 on 2022-05-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0067_auto_20220510_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodorder',
            name='recommended_restaurants',
        ),
    ]
